== MachinekitNotes

This repository contains Cerna's personal notes and thoughts on the Machinekit project and it's codebase, mainly the Machinetalk and HALtalk functionality.

**This is not a documentation for Machinekit in any meaning of the word.** The whole idea of this repository is to write down my delving attempts to understand the Machinekit codebase and create notes for my own personal needs.

== Glossary
=== Machinekit Instance
Machinekit Instance (MKI) is every installation of Machinekit which is able to perform core operations. (For example Machinekit and Machinekit-HAL repositories.) Each MKI is uniquely identified by it's GUID (UUID).

=== Machinetalk Service

=== Machinekit GUID (UUID)
Machinekit GUID or UUID uniquely identifies Machinekit Instance in scope of system installation. It is used for addressing purposes.

=== System installation
Space defined by networks on which MKIs communicate with each other, on which third party applications communicate with MKIs or networks where DNS-SD announcements are propagated.
